[package]
name = "xray-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-conf = { path = "../xray-conf" }
tokio = { workspace = true }
tracing = { workspace = true }
