//! GeoIP data types and convenience methods.
//!
//! Provides helpers for constructing and querying [`GeoIp`], [`Cidr`],
//! and related protobuf types generated by prost.

use crate::pb::{Cidr, GeoIp, GeoIpList};

// ── CIDR helpers ──────────────────────────────────────────────

impl Cidr {
    /// Creates a new CIDR from raw IP bytes and a prefix length.
    ///
    /// # Examples
    ///
    /// ```
    /// use xray_geodata::pb::Cidr;
    /// let cidr = Cidr::new(vec![192, 168, 0, 0], 16);
    /// assert_eq!(cidr.prefix, 16);
    /// ```
    pub fn new(ip: Vec<u8>, prefix: u32) -> Self {
        Self { ip, prefix }
    }

    /// Creates a CIDR representing an IPv4 address.
    ///
    /// `addr` must be exactly 4 bytes; returns `None` otherwise.
    pub fn from_ipv4(addr: [u8; 4], prefix: u32) -> Option<Self> {
        if prefix > 32 {
            return None;
        }
        Some(Self { ip: addr.to_vec(), prefix })
    }

    /// Creates a CIDR representing an IPv6 address.
    ///
    /// `addr` must be exactly 16 bytes; returns `None` otherwise.
    pub fn from_ipv6(addr: [u8; 16], prefix: u32) -> Option<Self> {
        if prefix > 128 {
            return None;
        }
        Some(Self { ip: addr.to_vec(), prefix })
    }

    /// Returns `true` if the IP bytes are 4 bytes long (IPv4).
    pub fn is_ipv4(&self) -> bool {
        self.ip.len() == 4
    }

    /// Returns `true` if the IP bytes are 16 bytes long (IPv6).
    pub fn is_ipv6(&self) -> bool {
        self.ip.len() == 16
    }
}

// ── GeoIP helpers ─────────────────────────────────────────────

impl GeoIp {
    /// Creates a new GeoIP entry with the given country code.
    ///
    /// # Examples
    ///
    /// ```
    /// use xray_geodata::pb::GeoIp;
    /// let geo = GeoIp::new("CN");
    /// assert_eq!(geo.code, "CN");
    /// ```
    pub fn new(code: &str) -> Self {
        Self { code: code.to_string(), cidr: Vec::new(), reverse_match: false }
    }

    /// Adds a CIDR entry and returns `self` for chaining.
    ///
    /// # Examples
    ///
    /// ```
    /// use xray_geodata::pb::{Cidr, GeoIp};
    /// let geo = GeoIp::new("US").with_cidr(Cidr::new(vec![10, 0, 0, 0], 8));
    /// assert_eq!(geo.cidr.len(), 1);
    /// ```
    pub fn with_cidr(mut self, cidr: Cidr) -> Self {
        self.cidr.push(cidr);
        self
    }

    /// Sets the reverse-match flag and returns `self` for chaining.
    pub fn with_reverse_match(mut self, reverse: bool) -> Self {
        self.reverse_match = reverse;
        self
    }
}

// ── GeoIPList helpers ─────────────────────────────────────────

impl GeoIpList {
    /// Creates an empty GeoIP list.
    pub fn new() -> Self {
        Self { entry: Vec::new() }
    }

    /// Adds a GeoIP entry and returns `self` for chaining.
    pub fn with_entry(mut self, entry: GeoIp) -> Self {
        self.entry.push(entry);
        self
    }

    /// Looks up a GeoIP entry by country code (case-insensitive).
    pub fn find_by_code(&self, code: &str) -> Option<&GeoIp> {
        let code_upper = code.to_uppercase();
        self.entry.iter().find(|e| e.code.to_uppercase() == code_upper)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── CIDR tests ────────────────────────────────────────────

    #[test]
    fn cidr_new_ipv4() {
        let cidr = Cidr::new(vec![192, 168, 1, 0], 24);
        assert_eq!(cidr.ip, vec![192, 168, 1, 0]);
        assert_eq!(cidr.prefix, 24);
        assert!(cidr.is_ipv4());
        assert!(!cidr.is_ipv6());
    }

    #[test]
    fn cidr_from_ipv4_valid() {
        let cidr = Cidr::from_ipv4([10, 0, 0, 0], 8);
        assert!(cidr.is_some());
        let cidr = cidr.unwrap();
        assert_eq!(cidr.ip, vec![10, 0, 0, 0]);
        assert_eq!(cidr.prefix, 8);
    }

    #[test]
    fn cidr_from_ipv4_invalid_prefix() {
        assert!(Cidr::from_ipv4([10, 0, 0, 0], 33).is_none());
    }

    #[test]
    fn cidr_from_ipv6_valid() {
        let addr = [0u8; 16];
        let cidr = Cidr::from_ipv6(addr, 64);
        assert!(cidr.is_some());
        let cidr = cidr.unwrap();
        assert!(cidr.is_ipv6());
        assert!(!cidr.is_ipv4());
        assert_eq!(cidr.prefix, 64);
    }

    #[test]
    fn cidr_from_ipv6_invalid_prefix() {
        let addr = [0u8; 16];
        assert!(Cidr::from_ipv6(addr, 129).is_none());
    }

    // ── GeoIP tests ───────────────────────────────────────────

    #[test]
    fn geoip_new() {
        let geo = GeoIp::new("CN");
        assert_eq!(geo.code, "CN");
        assert!(geo.cidr.is_empty());
        assert!(!geo.reverse_match);
    }

    #[test]
    fn geoip_builder_pattern() {
        let geo = GeoIp::new("US")
            .with_cidr(Cidr::new(vec![10, 0, 0, 0], 8))
            .with_cidr(Cidr::new(vec![172, 16, 0, 0], 12))
            .with_reverse_match(true);
        assert_eq!(geo.cidr.len(), 2);
        assert!(geo.reverse_match);
    }

    // ── GeoIPList tests ───────────────────────────────────────

    #[test]
    fn geoip_list_new() {
        let list = GeoIpList::new();
        assert!(list.entry.is_empty());
    }

    #[test]
    fn geoip_list_default() {
        let list = GeoIpList::default();
        assert!(list.entry.is_empty());
    }

    #[test]
    fn geoip_list_with_entry() {
        let list = GeoIpList::new().with_entry(GeoIp::new("CN")).with_entry(GeoIp::new("US"));
        assert_eq!(list.entry.len(), 2);
    }

    #[test]
    fn geoip_list_find_by_code() {
        let list = GeoIpList::new().with_entry(GeoIp::new("CN")).with_entry(GeoIp::new("US"));
        assert!(list.find_by_code("cn").is_some());
        assert!(list.find_by_code("US").is_some());
        assert!(list.find_by_code("JP").is_none());
    }

    // ── Serialization round-trip ──────────────────────────────

    #[test]
    fn geoip_roundtrip() {
        let original = GeoIp::new("CN")
            .with_cidr(Cidr::new(vec![192, 168, 0, 0], 16))
            .with_reverse_match(false);

        let bytes = prost::Message::encode_to_vec(&original);
        let decoded: GeoIp = prost::Message::decode(bytes.as_slice()).unwrap();
        assert_eq!(decoded.code, "CN");
        assert_eq!(decoded.cidr.len(), 1);
        assert_eq!(decoded.cidr[0].ip, vec![192, 168, 0, 0]);
        assert_eq!(decoded.cidr[0].prefix, 16);
        assert!(!decoded.reverse_match);
    }

    #[test]
    fn geoip_list_roundtrip() {
        let original = GeoIpList::new()
            .with_entry(GeoIp::new("CN").with_cidr(Cidr::new(vec![10, 0, 0, 0], 8)))
            .with_entry(GeoIp::new("US").with_cidr(Cidr::new(vec![172, 16, 0, 0], 12)));

        let bytes = prost::Message::encode_to_vec(&original);
        let decoded: GeoIpList = prost::Message::decode(bytes.as_slice()).unwrap();
        assert_eq!(decoded.entry.len(), 2);
        assert_eq!(decoded.entry[0].code, "CN");
        assert_eq!(decoded.entry[1].code, "US");
    }
}
