//! GeoSite data types and convenience methods.
//!
//! Provides helpers for constructing and querying [`GeoSite`],
//! [`Domain`], and related protobuf types generated by prost.

use crate::pb::{Domain, GeoSite, GeoSiteList};

// Re-export nested types for convenience
pub use crate::pb::domain::Attribute as DomainAttribute;
pub use crate::pb::domain::Type as DomainType;
pub use crate::pb::domain::attribute::TypedValue;

// ── Domain helpers ────────────────────────────────────────────

impl Domain {
    /// Creates a new Domain with the given type and value.
    ///
    /// # Examples
    ///
    /// ```
    /// use xray_geodata::pb::{Domain, domain::Type};
    /// let d = Domain::new(Type::Full, "example.com");
    /// assert_eq!(d.value, "example.com");
    /// ```
    pub fn new(r#type: impl Into<i32>, value: &str) -> Self {
        Self {
            r#type: r#type.into(),
            value: value.to_string(),
            attribute: Vec::new(),
        }
    }

    /// Creates a Domain with [`Type::Full`](DomainType::Full).
    pub fn full(value: &str) -> Self {
        Self::new(DomainType::Full as i32, value)
    }

    /// Creates a Domain with [`Type::Domain`](DomainType::Domain).
    pub fn domain(value: &str) -> Self {
        Self::new(DomainType::Domain as i32, value)
    }

    /// Creates a Domain with [`Type::Regex`](DomainType::Regex).
    pub fn regex(value: &str) -> Self {
        Self::new(DomainType::Regex as i32, value)
    }

    /// Creates a Domain with [`Type::Substr`](DomainType::Substr).
    pub fn substr(value: &str) -> Self {
        Self::new(DomainType::Substr as i32, value)
    }

    /// Adds an attribute and returns `self` for chaining.
    pub fn with_attribute(mut self, attr: DomainAttribute) -> Self {
        self.attribute.push(attr);
        self
    }
}

// ── DomainAttribute helpers ───────────────────────────────────

impl DomainAttribute {
    /// Creates a boolean attribute.
    pub fn bool_attr(key: &str, value: bool) -> Self {
        Self {
            key: key.to_string(),
            typed_value: Some(TypedValue::BoolValue(value)),
        }
    }

    /// Creates an integer attribute.
    pub fn int_attr(key: &str, value: i64) -> Self {
        Self {
            key: key.to_string(),
            typed_value: Some(TypedValue::IntValue(value)),
        }
    }
}

// ── GeoSite helpers ───────────────────────────────────────────

impl GeoSite {
    /// Creates a new GeoSite with the given country code.
    ///
    /// # Examples
    ///
    /// ```
    /// use xray_geodata::pb::GeoSite;
    /// let site = GeoSite::new("CN");
    /// assert_eq!(site.code, "CN");
    /// ```
    pub fn new(code: &str) -> Self {
        Self {
            code: code.to_string(),
            domain: Vec::new(),
        }
    }

    /// Adds a domain rule and returns `self` for chaining.
    ///
    /// # Examples
    ///
    /// ```
    /// use xray_geodata::pb::{Domain, GeoSite};
    /// let site = GeoSite::new("CN")
    ///     .with_domain(Domain::full("baidu.com"));
    /// assert_eq!(site.domain.len(), 1);
    /// ```
    pub fn with_domain(mut self, domain: Domain) -> Self {
        self.domain.push(domain);
        self
    }
}

// ── GeoSiteList helpers ───────────────────────────────────────

impl GeoSiteList {
    /// Creates an empty GeoSite list.
    pub fn new() -> Self {
        Self {
            entry: Vec::new(),
        }
    }

    /// Adds a GeoSite entry and returns `self` for chaining.
    pub fn with_entry(mut self, entry: GeoSite) -> Self {
        self.entry.push(entry);
        self
    }

    /// Looks up a GeoSite entry by country code (case-insensitive).
    pub fn find_by_code(&self, code: &str) -> Option<&GeoSite> {
        let code_upper = code.to_uppercase();
        self.entry
            .iter()
            .find(|e| e.code.to_uppercase() == code_upper)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pb::{Domain, GeoSite, GeoSiteList};

    // ── Domain tests ──────────────────────────────────────────

    #[test]
    fn domain_full() {
        let d = Domain::full("example.com");
        assert_eq!(d.r#type, DomainType::Full as i32);
        assert_eq!(d.value, "example.com");
        assert!(d.attribute.is_empty());
    }

    #[test]
    fn domain_domain_type() {
        let d = Domain::domain("google");
        assert_eq!(d.r#type, DomainType::Domain as i32);
    }

    #[test]
    fn domain_regex() {
        let d = Domain::regex(r"\.cn$");
        assert_eq!(d.r#type, DomainType::Regex as i32);
    }

    #[test]
    fn domain_substr() {
        let d = Domain::substr("evil");
        assert_eq!(d.r#type, DomainType::Substr as i32);
    }

    #[test]
    fn domain_with_attribute() {
        let d = Domain::full("example.com")
            .with_attribute(DomainAttribute::bool_attr("tls", true))
            .with_attribute(DomainAttribute::int_attr("port", 443));
        assert_eq!(d.attribute.len(), 2);
        assert_eq!(d.attribute[0].key, "tls");
        assert_eq!(d.attribute[1].key, "port");
    }

    // ── DomainAttribute tests ─────────────────────────────────

    #[test]
    fn attribute_bool() {
        let attr = DomainAttribute::bool_attr("tls", true);
        assert_eq!(attr.key, "tls");
        match &attr.typed_value {
            Some(TypedValue::BoolValue(v)) => {
                assert!(*v);
            }
            _ => panic!("expected bool_value"),
        }
    }

    #[test]
    fn attribute_int() {
        let attr = DomainAttribute::int_attr("port", 8080);
        assert_eq!(attr.key, "port");
        match &attr.typed_value {
            Some(TypedValue::IntValue(v)) => {
                assert_eq!(*v, 8080);
            }
            _ => panic!("expected int_value"),
        }
    }

    // ── GeoSite tests ─────────────────────────────────────────

    #[test]
    fn geosite_new() {
        let site = GeoSite::new("CN");
        assert_eq!(site.code, "CN");
        assert!(site.domain.is_empty());
    }

    #[test]
    fn geosite_builder_pattern() {
        let site = GeoSite::new("US")
            .with_domain(Domain::full("google.com"))
            .with_domain(Domain::domain("facebook"));
        assert_eq!(site.domain.len(), 2);
    }

    // ── GeoSiteList tests ─────────────────────────────────────

    #[test]
    fn geosite_list_new() {
        let list = GeoSiteList::new();
        assert!(list.entry.is_empty());
    }

    #[test]
    fn geosite_list_default() {
        let list = GeoSiteList::default();
        assert!(list.entry.is_empty());
    }

    #[test]
    fn geosite_list_with_entry() {
        let list = GeoSiteList::new()
            .with_entry(GeoSite::new("CN"))
            .with_entry(GeoSite::new("US"));
        assert_eq!(list.entry.len(), 2);
    }

    #[test]
    fn geosite_list_find_by_code() {
        let list = GeoSiteList::new()
            .with_entry(GeoSite::new("CN"))
            .with_entry(GeoSite::new("US"));
        assert!(list.find_by_code("cn").is_some());
        assert!(list.find_by_code("US").is_some());
        assert!(list.find_by_code("JP").is_none());
    }

    // ── Serialization round-trip ──────────────────────────────

    #[test]
    fn domain_roundtrip() {
        let original = Domain::full("example.com")
            .with_attribute(DomainAttribute::bool_attr("tls", true));

        let bytes = prost::Message::encode_to_vec(&original);
        let decoded: Domain =
            prost::Message::decode(bytes.as_slice()).unwrap();
        assert_eq!(decoded.r#type, DomainType::Full as i32);
        assert_eq!(decoded.value, "example.com");
        assert_eq!(decoded.attribute.len(), 1);
    }

    #[test]
    fn geosite_roundtrip() {
        let original = GeoSite::new("CN")
            .with_domain(Domain::full("baidu.com"))
            .with_domain(Domain::regex(r"\.cn$"));

        let bytes = prost::Message::encode_to_vec(&original);
        let decoded: GeoSite =
            prost::Message::decode(bytes.as_slice()).unwrap();
        assert_eq!(decoded.code, "CN");
        assert_eq!(decoded.domain.len(), 2);
        assert_eq!(decoded.domain[0].value, "baidu.com");
        assert_eq!(
            decoded.domain[1].r#type,
            DomainType::Regex as i32
        );
    }

    #[test]
    fn geosite_list_roundtrip() {
        let original = GeoSiteList::new()
            .with_entry(
                GeoSite::new("CN")
                    .with_domain(Domain::full("baidu.com")),
            )
            .with_entry(
                GeoSite::new("US")
                    .with_domain(Domain::domain("google")),
            );

        let bytes = prost::Message::encode_to_vec(&original);
        let decoded: GeoSiteList =
            prost::Message::decode(bytes.as_slice()).unwrap();
        assert_eq!(decoded.entry.len(), 2);
        assert_eq!(decoded.entry[0].code, "CN");
        assert_eq!(decoded.entry[1].code, "US");
    }
}