[package]
name = "xray-proxy-tun"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
thiserror = { workspace = true }
xray-transport = { path = "../xray-transport" }
xray-app-dispatcher = { path = "../xray-app-dispatcher" }
parking_lot = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tun-rs = { workspace = true }
smoltcp = { workspace = true }
async-trait = { workspace = true }
