[package]
name = "xray-features"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
async-trait = "0.1"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt", "net"] }
parking_lot = { workspace = true }
[dev-dependencies]
tokio = { workspace = true }
