[package]
name = "xray-transport-websocket"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-buf = { path = "../xray-buf" }
xray-common = { path = "../xray-common" }
xray-transport = { path = "../xray-transport" }
xray-proto = { path = "../xray-proto" }
xray-tls = { path = "../xray-tls" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
sha1 = "0.10"
base64 = "0.22"
tokio-tungstenite.workspace = true
tokio-rustls = { workspace = true }
rustls-pki-types.workspace = true
rustls.workspace = true
futures-util = "0.3"
http = "1"

[dev-dependencies]
rcgen = "0.13"
