[package]
name = "xray-transport-quic"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-buf = { path = "../xray-buf" }
xray-common = { path = "../xray-common" }
xray-transport = { path = "../xray-transport" }
xray-tls = { path = "../xray-tls" }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rustls = { workspace = true }
bytes = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
