[package]
name = "xray-transport-httpupgrade"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-buf = { path = "../xray-buf" }
xray-common = { path = "../xray-common" }
xray-transport = { path = "../xray-transport" }
xray-tls = { path = "../xray-tls" }
xray-proto = { path = "../xray-proto" }
serde_json = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tokio-rustls = { workspace = true }
