[package]
name = "xray-transport-hysteria"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-buf = { path = "../xray-buf" }
xray-common = { path = "../xray-common" }
xray-transport = { path = "../xray-transport" }
tokio = { workspace = true }
tracing = { workspace = true }
