[package]
name = "xray-app-metrics"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-proto = { path = "../xray-proto" }
thiserror = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt", "rt-multi-thread", "net", "io-util", "macros", "time"] }
tracing = { workspace = true }
