[package]
name = "xray-proxy-wireguard"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-proto = { path = "../xray-proto" }
xray-app-dispatcher = { path = "../xray-app-dispatcher" }
xray-transport = { path = "../xray-transport" }
xray-xudp = { path = "../xray-xudp" }
xray-app-dns = { path = "../xray-app-dns" }
xray-buf = { path = "../xray-buf" }
xray-app-proxyman = { path = "../xray-app-proxyman" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
boringtun = { workspace = true }
hex = "0.4"
smoltcp = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
