[package]
name = "xray-proxy-hysteria"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-proto = { path = "../xray-proto" }
xray-transport-hysteria = { path = "../xray-transport-hysteria" }
xray-app-dispatcher = { path = "../xray-app-dispatcher" }
xray-xudp = { path = "../xray-xudp" }
xray-transport = { path = "../xray-transport" }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
quinn = { workspace = true }
rand = { workspace = true }
prost = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
bytes = { workspace = true }
rcgen = "0.13"
rustls = { workspace = true, default-features = false, features = ["ring"] }
rustls-pki-types = { workspace = true }
