[package]
name = "xray-app-dns"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-geodata = { path = "../xray-geodata" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
parking_lot.workspace = true
uuid.workspace = true
lru = "0.12"
hickory-proto.workspace = true
ipnet = "2"
xray-tls = { path = "../xray-tls" }
xray-transport = { path = "../xray-transport" }
tokio-rustls.workspace = true
h2.workspace = true
http.workspace = true
bytes.workspace = true
quinn.workspace = true

[dev-dependencies]
rcgen = "0.13"
