[package]
name = "xray-app-dns"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-geodata = { path = "../xray-geodata" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
parking_lot.workspace = true
uuid.workspace = true
lru = "0.12"
ipnet = "2"
