[package]
name = "xray-app-commander"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-proto = { path = "../xray-proto", features = ["grpc-server"] }
xray-app-stats = { path = "../xray-app-stats" }
xray-app-router = { path = "../xray-app-router" }
xray-app-log = { path = "../xray-app-log" }
xray-app-observatory = { path = "../xray-app-observatory" }
xray-app-proxyman = { path = "../xray-app-proxyman" }
xray-app-dispatcher = { path = "../xray-app-dispatcher" }
xray-transport = { path = "../xray-transport" }
thiserror = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["io-util", "sync", "rt", "net"] }
async-trait = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }
prost = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
xray-proto = { path = "../xray-proto", features = ["grpc-client"] }
xray-buf = { path = "../xray-buf" }
hyper-util = { workspace = true }
