[package]
name = "xray-app-reverse"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-proto = { path = "../xray-proto" }
thiserror = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "time", "macros", "sync"] }
yamux = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
