[package]
name = "xray-app-dispatcher"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-buf = { path = "../xray-buf" }
xray-transport = { path = "../xray-transport" }
xray-proto = { path = "../xray-proto" }
xray-xudp = { path = "../xray-xudp" }
thiserror.workspace = true
tokio.workspace = true
rand = { workspace = true }
tracing.workspace = true
parking_lot.workspace = true
httparse.workspace = true
ring.workspace = true

[dev-dependencies]
xray-app-stats = { path = "../xray-app-stats" }
