[package]
name = "xray-transport-grpc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-buf = { path = "../xray-buf" }
xray-common = { path = "../xray-common" }
xray-transport = { path = "../xray-transport" }
xray-proto = { path = "../xray-proto" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
prost = { workspace = true }
