[package]
name = "xray-transport-grpc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-buf = { path = "../xray-buf" }
xray-common = { path = "../xray-common" }
xray-transport = { path = "../xray-transport" }
xray-proto = { path = "../xray-proto" }
xray-tls = { path = "../xray-tls", optional = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
prost = { workspace = true }
flate2 = { workspace = true }
h2 = "0.4"
http = "1"
bytes = "1"
tokio-rustls = { workspace = true }
rustls = { workspace = true }

[features]
default = ["register"]
register = ["dep:xray-tls"]
