[package]
name = "xray-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-buf = { path = "../xray-buf" }
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-crypto = { path = "../xray-crypto" }
thiserror = "1"
tokio = { workspace = true }
tracing = { workspace = true }
socket2 = { workspace = true }
parking_lot = { workspace = true }
tokio-tungstenite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
base64 = "0.22"
blake2 = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }
futures-util = "0.3"
rustls = { workspace = true }
ring = { workspace = true }
# xmc (finalmask Minecraft 伪装)：AES-CFB8 + RSA-1024 PKCS1v15 + 确定性素数派生
aes = "0.9"
rsa = "0.9"
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
