[package]
name = "xray-proxy-dns"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-features = { path = "../xray-features" }
xray-proto = { path = "../xray-proto" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
xray-geodata = { path = "../xray-geodata" }
hickory-resolver = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
hickory-resolver = { workspace = true }
tokio = { workspace = true, features = ["full", "test-util"] }
