[package]
name = "xray-proxy-tuic"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-transport = { path = "../xray-transport" }
xray-app-dispatcher = { path = "../xray-app-dispatcher" }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
quinn = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
rcgen = "0.13"

xray-features = { path = "../xray-features" }
xray-buf = { path = "../xray-buf" }
async-trait = { workspace = true }

[dev-dependencies]
xray-proxy-freedom = { path = "../xray-proxy-freedom" }
tokio = { workspace = true, features = ["full", "test-util"] }
parking_lot = { workspace = true }
rcgen = "0.13"
