[package]
name = "xray-proxy-anytls"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
xray-common = { path = "../xray-common" }
xray-transport = { path = "../xray-transport" }
xray-app-dispatcher = { path = "../xray-app-dispatcher" }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
anytls = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
rcgen = "0.13"
xray-buf = { path = "../xray-buf" }
xray-app-dispatcher = { path = "../xray-app-dispatcher" }
